// <auto-generated />
using EsisaSurvey.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EsisaSurvey.Migrations
{
    [DbContext(typeof(EfCore))]
    partial class EfCoreModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EsisaSurvey.Models.ChangeSurveyModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Json");

                    b.Property<string>("Text");

                    b.Property<int>("commercantId");

                    b.HasKey("Id");

                    b.HasIndex("commercantId");

                    b.ToTable("Survey");
                });

            modelBuilder.Entity("EsisaSurvey.Models.Client", b =>
                {
                    b.Property<int>("clientid")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("adress");

                    b.Property<string>("email");

                    b.Property<string>("login");

                    b.Property<string>("name");

                    b.Property<string>("password");

                    b.HasKey("clientid");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("EsisaSurvey.Models.Commercant", b =>
                {
                    b.Property<int>("commercantId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Entreprise");

                    b.Property<string>("commercantName");

                    b.Property<string>("login");

                    b.Property<string>("password");

                    b.HasKey("commercantId");

                    b.ToTable("Commercant");
                });

            modelBuilder.Entity("EsisaSurvey.Models.PostSurveyResultModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("clientid");

                    b.Property<string>("postId");

                    b.Property<string>("surveyResult");

                    b.HasKey("id");

                    b.HasIndex("clientid");

                    b.ToTable("SurveyResult");
                });

            modelBuilder.Entity("EsisaSurvey.Models.Survey", b =>
                {
                    b.Property<int>("surveyIdBE")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Id");

                    b.Property<string>("Json");

                    b.Property<string>("Text");

                    b.Property<int>("commercantId");

                    b.HasKey("surveyIdBE");

                    b.HasIndex("commercantId");

                    b.ToTable("SurveyStore");
                });

            modelBuilder.Entity("EsisaSurvey.Models.SurveyResultLog", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("clientId");

                    b.Property<string>("postId");

                    b.Property<string>("surveyanswerJson");

                    b.HasKey("id");

                    b.ToTable("SurveyResulLog");
                });

            modelBuilder.Entity("EsisaSurvey.Models.ChangeSurveyModel", b =>
                {
                    b.HasOne("EsisaSurvey.Models.Commercant", "Commercant")
                        .WithMany()
                        .HasForeignKey("commercantId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EsisaSurvey.Models.PostSurveyResultModel", b =>
                {
                    b.HasOne("EsisaSurvey.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("clientid")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EsisaSurvey.Models.Survey", b =>
                {
                    b.HasOne("EsisaSurvey.Models.Commercant", "Commercant")
                        .WithMany()
                        .HasForeignKey("commercantId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
